export const Routes = {
    First: '/',
    Home: '/Home',
    Login: '/login',
    Ntantades: 'ntantades',
    Eisagogi: '/Eisagogi',
    ProsopikaStoixeia: '/ProsopikaStoixeia',
    EpisinapsiArxeion: '/EpisinapsiArxeion',
    DhmiourgiaAggelias: '/DhmiourgiaAggelias',
    TelikiYpobolh: '/TelikiYpobolh',
    CV: '/CV',
    Details: '/Details',
    LoginVerification: '/loginVerification',
    AitisiSimmetoxis: '/aitisi-simmetoxis',
    SearchProfessional: 'search-professional',
    Professional: ':professionalId',
    Application: `/aitisi-simmetoxis/:applicationId`,
    Meeting: 'sinantiseis',
    ApplicationsWithProfessionals: 'aitiseis',
    Agreement: 'simfonitika',
    WorkCertification: 'pistopoiitiko-ergasias'
};